-- DB Nutzer erstellen, der die selben Rechte besitzt, wie alle TH-Wildau Nutzer
CREATE USER "LABORMANAGEMENT"
IDENTIFIED BY "LABORMANAGEMENT"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

GRANT CREATE MATERIALIZED VIEW TO "LABORMANAGEMENT";
GRANT CREATE PROCEDURE TO "LABORMANAGEMENT";
GRANT CREATE SEQUENCE TO "LABORMANAGEMENT";
GRANT CREATE SESSION TO "LABORMANAGEMENT";
GRANT CREATE SYNONYM TO "LABORMANAGEMENT";
GRANT CREATE TABLE TO "LABORMANAGEMENT";
GRANT CREATE TRIGGER TO "LABORMANAGEMENT";
GRANT CREATE TYPE TO "LABORMANAGEMENT";
GRANT CREATE VIEW TO "LABORMANAGEMENT";

ALTER USER "LABORMANAGEMENT" QUOTA 102400K ON USERS;